name: Deploy Action
description: Deploy Action

runs:
  using: "composite"
  steps:
    - name: Build
      id: build
      run: |
        echo "Building using directory"
      shell: bash

    - name: Deploy
      id: deploy
      run: |
        echo "Deploying build artifacts"
      shell: bash
     
