name:  16 - 2 - Custom Action.
on:
    workflow_dispatch:
jobs:
    main-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: deploy
              uses: ./.github/deploy-action
              
